#!/bin/sh
### BEGIN INIT INFO
# Provides:          pdfwam
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start pdfwam
# Description:       Provides Tingtun PDF accessiblity daemon.
### END INIT INFO
# /etc/init.d scripts for managing PDF-WAM

NAME=pdfwam
DESC="Tingtun PDF accessibility checking daemon"
SERVER=pdfwam
SEARCHPATHS="/home/anand/pdfwam/ /home/anand/norway/pdfwam/ /home/anand/PdfWam/"

find_exe_path () {

 for path in $SEARCHPATHS 
 do
    if [ -f $path$NAME ];
    then
        local mypath=$path$NAME;
        echo "$mypath";
    fi
    
 done
}

DAEMON=;
START_DAEMON="yes";
PIDFILE="/var/run/pdfwam.pid"

. /lib/lsb/init-functions

check_pid()
{
    if test -f "$PIDFILE"; then
        log_warning_msg "pid file is exist in $PIDFILE, stop or restart PdfWam"
        exit 0
    fi
}

is_yes() {
    case "$1" in
        [Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|1) return 0;;
        *) return 1;
    esac
}

pdfwam_start()
{
    DAEMON=`find_exe_path`;
    if is_yes "$START_DAEMON"; then
        echo "Found $DAEMON"
        # check_pid
        log_begin_msg "Starting $NAME"
        /sbin/start-stop-daemon --oknodo --start --quiet --pidfile "$PIDFILE" \
            --exec "$DAEMON" -- --daemon -p "$PIDFILE" $START_OPTIONS
        log_end_msg $?
    else
        log_warning_msg "Not starting $NAME (disabled in /etc/default/$NAME)"
    fi
}

pdfwam_stop()
{
    DAEMON=`find_exe_path`;
    log_begin_msg "Stopping $NAME"
     /sbin/start-stop-daemon --oknodo --stop --quiet --pidfile "$PIDFILE"
     log_end_msg $?
    rm -f $PIDFILE;
}

pdfwam_status()
{
    [ -f "$PIDFILE" ] && echo "pdfwam is running."
    [ ! -f "$PIDFILE" ] && echo "pdfwam is not running."
}

case "$1" in
  start)
    pdfwam_start
    ;;
  stop)
    pdfwam_stop
  ;;
  status)
    pdfwam_status
    ;;
  restart|force-reload)
    pdfwam_stop
    pdfwam_start
    ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
